
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='OneLauncher',
    version='1.2.8',
    description='The OneLauncher for LOTRO and DDO',
    python_requires='<3.10,>=3.9',
    author='Jeremy Stepp',
    author_email='contact@jeremystepp.me',
    license='GPL-3.0-or-later',
    entry_points={"console_scripts": ["onelauncher = OneLauncher.Runner:main"]},
    packages=['OneLauncher'],
    package_dir={"": "."},
    package_data={"OneLauncher": ["certificates/*.pem", "images/*.ico", "images/*.png", "ui/*.ui"]},
    install_requires=['cryptography==3.*,>=3.4.7', 'defusedxml==0.*,>=0.7.1', 'keyring==23.*,>=23.0.1', 'pyside6==6.0.4', 'qdarkstyle', 'qtpy', 'vkbeautify==0.*,>=0.3.0'],
    dependency_links=['git+https://github.com/JeremyStepp/QDarkStyleSheet.git#egg=qdarkstyle', 'git+https://github.com/jschueller/qtpy.git@qt6#egg=qtpy'],
    extras_require={"dev": ["bandit==1.*,>=1.7.0", "black==20.*,>=20.8.0.b1", "cx-freeze==6.5.3", "pywin32==301.*,>=301.0.0"]},
)
